spring:
  application:
    name: Fitseek-plan
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ry-vue
    username: root
    password: mzyudada

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

server:
  port: 8080
logging:
  level:
    com.baomidou.mybatisplus: debug
